name: Deploy to Azure Function

on:
  push:
    branches:
      - dev  # Adjust to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Azure using Service Principal
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Disable OIDC authentication
          auth-type: "SERVICE_PRINCIPAL"

      # Step 3: Deploy to Azure Function App using a ZIP file
      - name: Deploy to Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --src ./publish.zip  # Path to the ZIP file of your app

      # Optional: Clear Azure login credentials (for security purposes)
      - name: Logout from Azure
        run: |
          az logout
