name: Azure Deployment

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Grant permission to request ID token


    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    # Log in to Azure (authentication using service principal)
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: "SERVICE_PRINCIPAL"
        enable-AzPSSession: false
        environment: "azurecloud"
        allow-no-subscriptions: false
        audience: "api://AzureADTokenExchange"

    # Build the .NET application (only if needed)
    - name: Build the application
      run: |
        dotnet restore
        dotnet build --configuration Release

    # Publish the application
    - name: Publish the application
      run: |
        dotnet publish --configuration Release --output ./publish

    # Step to deploy to Azure Functions (replace with your correct app info)
    - name: Deploy to Azure Function App
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az functionapp deployment source config-zip \
        --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
        --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
        --src ./publish.zip

    # Clean up if necessary
    - name: Cleanup
      run: |
        echo "Cleaning up resources"
