name: Deploy to Azure Function

on:
  push:
    branches:
      - dev  # Trigger on push to dev branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x' # Specify the .NET version you are using

      - name: Publish the .NET app
        run: |
          dotnet publish -c Release -o ./publish

      - name: Zip the published app
        run: |
          cd ./publish
          zip -r ../publish.zip .  # Create a ZIP file for deployment

      # Step 2: Log in to Azure using Service Principal.
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Function
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --src ./publish.zip  # Path to the ZIP file of your app

      - name: Logout from Azure
        run: |
          az logout