name: .NET Core CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    # Set up .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.0' # Specify the .NET version you are using

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the solution
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Run tests
    - name: Run tests
      run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

    # List files to verify test results
    - name: List files
      if: always()
      run: ls -R ./TLP-API.Tests

    # Upload test results to GitHub Actions
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./TLP-API.Tests/TestResults/test_results.trx  # Corrected path

    # Publish test results to GitHub Releases
    - name: Publish test results
      uses: softprops/action-gh-release@v1
      with:
        files: test_results.trx
